Queueomatic/Queueomatic.DataAccess/Class1.cs, Queueomatic/Queueomatic.DataAccess/Queueomatic.DataAccess.csproj, Queueomatic/Queueomatic.sln
This pull request adds a class library which is supposed to contain our future datacontext, repositories and unit of work which closes #33.
=> Create data access project

Queueomatic/Server/Program.cs, Queueomatic/Server/Queueomatic.Server.csproj
This closes #28 by adding support for the Fast Endpoints.
=> Add support for fep

Queueomatic/Queueomatic.DataAccess/DataContexts/AppContext.cs, Queueomatic/Queueomatic.DataAccess/Queueomatic.DataAccess.csproj
Adds a data context with support for SQL Server and entity framework.
Closes #36.
=> Create data context

Queueomatic/Server/Program.cs, Queueomatic/Server/Queueomatic.Server.csproj
Adds support for hashids. We have to change our datamodel ids to ints, otherwise this package will not work.
Closes #29
=> Add hashids

.github/workflows/codeql.yml, .github/workflows/dotnetSecond.yml
Scans for vulnerabilities and or exposed secrets in our code.
=> Code analysis

Queueomatic/Queueomatic.Test/AuthenticationService_VerifySequence.cs, Queueomatic/Queueomatic.Test/Queueomatic.Test.csproj, Queueomatic/Server/Program.cs, Queueomatic/Server/Services/AuthenticationService/AuthenticationService.cs, Queueomatic/Server/Services/AuthenticationService/IAuthenticationService.cs
This adds an authentication service that can be used in our endpoints. 
The validation of credentials does not return a token because that is done in our login endpoint. FEP has built in support for it.
Closes #11
=> Create authentication service

Queueomatic/Queueomatic.Test/HashIdService_Tests.cs, Queueomatic/Server/Program.cs, Queueomatic/Server/Queueomatic.Server.csproj, Queueomatic/Server/Services/HashIdService/HashIdService.cs, Queueomatic/Server/Services/HashIdService/IHashIdService.cs, Queueomatic/Server/appsettings.json
Adds a hashid service which converts ints to hash ids.
Closes #72
=> Create hash id service

Queueomatic/Queueomatic.Test/CreateRoomService_ReturnCorrectValue.cs, Queueomatic/Server/Endpoints/Room/Add/AddNewRoomEndpoint.cs, Queueomatic/Server/Endpoints/Room/Add/AddNewRoomRequest.cs, Queueomatic/Server/Endpoints/Room/Add/AddNewRoomResponse.cs, Queueomatic/Server/Endpoints/Room/Add/AddNewRoomValidator.cs, Queueomatic/Server/Program.cs, Queueomatic/Server/Services/CreateRoomService/CreateRoomService.cs, Queueomatic/Server/Services/CreateRoomService/ICreateRoomService.cs, Queueomatic/Shared/Resources/Adjectives.cs, Queueomatic/Shared/Resources/Nouns.cs
It contains tests for the service.
=> Implement add new room endpoint

Queueomatic/Queueomatic.Test/RoomService_Tests.cs, Queueomatic/Server/Services/RoomService/IRoomService.cs, Queueomatic/Server/Services/RoomService/RoomService.cs
Fixes method names.
The hashid for the room can be decoded using the hashid service and then the room can be retrieved from the database.
=> Update room service

Queueomatic/Queueomatic.DataAccess/Repositories/UserRepository.cs, Queueomatic/Queueomatic.Test/CreateRoomService_ReturnCorrectValue.cs, Queueomatic/Server/Endpoints/Room/Add/AddNewRoomEndpoint.cs, Queueomatic/Server/Endpoints/Room/Add/AddNewRoomRequest.cs, Queueomatic/Server/Endpoints/Room/Add/AddNewRoomValidator.cs, Queueomatic/Server/Endpoints/User/GetByEmail/GetUserByEmailEndpoint.cs, Queueomatic/Server/Endpoints/User/GetByEmail/GetUserByEmailRequest.cs, Queueomatic/Server/Program.cs, Queueomatic/Server/Services/RoomService/IRoomService.cs, Queueomatic/Server/Services/RoomService/RoomService.cs
Adds an endpoint to retrieve the user by email if they are logged in or if an admin is querying something. 
Also simplified the room creation endpoint by changing the routing and the room service class since the DTO is not actually used. Only the name is used in the room creation method. 
The wiki will also be changed to reflect these updates.
Closes #62
=> Implement get user by email

Queueomatic/Queueomatic.Test/ParticipantService_AddParticipant.cs, Queueomatic/Server/Endpoints/Participant/Add/AddNewParticipantEndpoint.cs, Queueomatic/Server/Endpoints/Participant/Add/AddNewParticipantResponse.cs, Queueomatic/Server/Endpoints/Participant/Add/AddNewParticipantValidator.cs, Queueomatic/Server/Program.cs, Queueomatic/Server/Services/ParticipantService/IParticipantService.cs, Queueomatic/Server/Services/ParticipantService/ParticipantService.cs
This also includes #59. Room is needed for a participant to be saved in db therefore signing a participant up for a room can be done here. A Participant hits the endpoint through a specific room anyway.
Closes #54 and #59.
=> Feat: Add impelementaion of add new participant endpoint

Queueomatic/Queueomatic.Test/ParticipantService_AddParticipant.cs, Queueomatic/Server/Endpoints/Participant/Edit/EditParticipantEndpoint.cs, Queueomatic/Server/Endpoints/Participant/Edit/EditParticipantRequest.cs, Queueomatic/Server/Endpoints/Participant/Edit/EditParticipantResponse.cs, Queueomatic/Server/Services/ParticipantService/IParticipantService.cs, Queueomatic/Server/Services/ParticipantService/ParticipantService.cs
=> Implement edit participant endpoint

Queueomatic/Client/Queueomatic.Client.csproj, Queueomatic/Server/Program.cs
This PR adds the library [SignalR](https://dotnet.microsoft.com/en-us/apps/aspnet/signalr) to the client and server project.
Closes #85
=> Add SignalR

Queueomatic/Client/Components/Login/LoginComponent.cs, Queueomatic/Client/Components/Login/LoginComponent.razor, Queueomatic/Client/Components/Login/LoginComponent.razor.cs, Queueomatic/Client/Components/Login/LoginComponent.razor.css, Queueomatic/Client/Components/Logo/LogoComponent.razor, Queueomatic/Client/Components/Logo/LogoComponent.razor.css, Queueomatic/Client/Components/RedirectHome.razor, Queueomatic/Client/Pages/Index.razor, Queueomatic/Client/Pages/Login.razor, Queueomatic/Client/Shared/NavMenu.razor, Queueomatic/Client/_Imports.razor
Maybe we can have a header instead of `LogoComponent` which might be for all the pages?
close #92
=> Create login page

Queueomatic/Client/Components/SignUp/SignUpComponent.razor, Queueomatic/Client/Components/SignUp/SignUpComponent.razor.cs, Queueomatic/Client/Components/SignUp/SignUpComponent.razor.css, Queueomatic/Client/Pages/Login.razor, Queueomatic/Client/Pages/SignUp.razor, Queueomatic/Client/_Imports.razor, Queueomatic/Shared/DTOs/SignupDto.cs
=> Create sign up page

Queueomatic/Client/Components/Login/LoginComponent.razor, Queueomatic/Client/Components/Login/LoginComponent.razor.cs, Queueomatic/Client/Components/Login/LoginComponent.razor.css
Disabling the login button from sending new request until it gets a result. 
Also changed the redirection of users to correct content by checking the status code from calling endpoint.
=> Bug: Prevent login button from multi click

Queueomatic/Client/Components/SignUp/SignUpComponent.razor, Queueomatic/Client/Components/SignUp/SignUpComponent.razor.cs, Queueomatic/Client/Components/SignUp/SignUpComponent.razor.css
=> Style: Restyle the content of signup-button to its status

Queueomatic/Client/Components/SignUp/SignUpComponent.razor, Queueomatic/Client/Components/SignUp/SignUpComponent.razor.cs, Queueomatic/Client/Components/SignUp/SignUpComponent.razor.css, Queueomatic/Client/Queueomatic.Client.csproj, Queueomatic/Server/Endpoints/ForgetPassword/ForgetPasswordEndpoint.cs, Queueomatic/Server/Endpoints/ResetPassword/ResetPasswordEndpoint.cs
Close #131 and also close #126
=> Handle signup scenario where a user already exists

Queueomatic/Queueomatic.DataAccess/Repositories/Interfaces/IRoomRepository.cs, Queueomatic/Queueomatic.DataAccess/Repositories/RoomRepository.cs, Queueomatic/Server/BackgroundServices/ScopedBackgroundService.cs, Queueomatic/Server/Program.cs, Queueomatic/Server/Services/RoomDeletionService/IRoomDeletionService.cs, Queueomatic/Server/Services/RoomDeletionService/RoomDeletionService.cs
Any input on this implementation? 
It's based on [Microsoft](https://learn.microsoft.com/en-us/dotnet/core/extensions/scoped-service?pivots=dotnet-7-0)
=> Feat: Add auto deletion for the expired rooms

Queueomatic/Client/Pages/Logout.razor, Queueomatic/Client/Pages/Logout.razor.cs, Queueomatic/Client/Pages/Logout.razor.css, Queueomatic/Client/Shared/NavMenu.razor, Queueomatic/Client/Shared/NavMenu.razor.css
=> Feat: Add logout function

Queueomatic/Client/Components/Login/LoginComponent.razor, Queueomatic/Client/Components/Login/LoginComponent.razor.cs
=> Style: Change the response message from just a text to a toast

Queueomatic/Client/App.razor, Queueomatic/Client/Components/EditProfile/EditProfileComponent.razor, Queueomatic/Client/Components/EditProfile/EditProfileComponent.razor.cs, Queueomatic/Client/Components/EditProfile/EditProfileComponent.razor.css, Queueomatic/Client/Components/Login/LoginComponent.razor, Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor, Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor.cs, Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor.css, Queueomatic/Client/Components/Profile/ProfileComponent.razor, Queueomatic/Client/Components/Profile/ProfileComponent.razor.cs, Queueomatic/Client/Pages/Index.razor, Queueomatic/Client/Pages/Index.razor.cs, Queueomatic/Client/Pages/Index.razor.css, Queueomatic/Client/Program.cs, Queueomatic/Client/Queueomatic.Client.csproj, Queueomatic/Client/_Imports.razor, Queueomatic/Client/wwwroot/css/app.css
=> Change the modal on profile page to a blazoredmodal

Queueomatic/Client/App.razor, Queueomatic/Client/Components/Login/LoginComponent.razor, Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor, Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor.cs, Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor.css, Queueomatic/Client/Pages/Index.razor, Queueomatic/Client/Pages/Index.razor.cs, Queueomatic/Client/Pages/Index.razor.css, Queueomatic/Client/Program.cs, Queueomatic/Client/Queueomatic.Client.csproj, Queueomatic/Client/_Imports.razor, Queueomatic/Client/wwwroot/css/app.css
=> Add username input design and logic for the landing page

Queueomatic/Client/Pages/Index.razor.cs
Set an input check for checking the input for room id on the landing page.
Closes #150
=> Bug: Fix a input check on roomInput

Queueomatic/Client/wwwroot/index.html
Added drag-and-drop script for mobile.
Closes #116
=> Feat: Add drag and drop script for mobile

Queueomatic/Client/Pages/Room.razor, Queueomatic/Client/Pages/Room.razor.cs, Queueomatic/Client/Pages/Room.razor.css, Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs
Add a button on the room page and also its functionality to leave a room and broadcast the action.
Closes #145
=> Add exit button in the room page

Queueomatic/Client/Pages/Room.razor.cs, Queueomatic/Queueomatic.DataAccess/Repositories/RoomRepository.cs, Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs, Queueomatic/Server/Program.cs, Queueomatic/Server/Services/CacheRoomService/CacheRoomService.cs, Queueomatic/Server/Services/CacheRoomService/ICacheRoomService.cs, Queueomatic/Server/appsettings.json, Queueomatic/Shared/Models/RoomModel.cs
Added a caching service to quickly be able to update the room across multiple users. In the future we could look at using Redis instead, but for now this will work.
If we still want to have a permament persister we can create a separate point for that.
Fixes #146 #140
=> Fix bugs and add state persister

Queueomatic/Client/Components/CreateRoom/CreateRoomForm.razor, Queueomatic/Client/Components/CreateRoom/CreateRoomForm.razor.cs, Queueomatic/Client/Components/CreateRoom/CreateRoomForm.razor.css, Queueomatic/Client/Pages/Room.razor.cs, Queueomatic/Client/Queueomatic.Client.csproj, Queueomatic/Client/Shared/NavMenu.razor, Queueomatic/Client/_Imports.razor, Queueomatic/Queueomatic.Test/CreateRoomService_ReturnCorrectValue.cs, Queueomatic/Server/Endpoints/Room/Add/AddNewRoomEndpoint.cs, Queueomatic/Server/Endpoints/Room/Add/AddNewRoomResponse.cs, Queueomatic/Server/Services/CacheRoomService/CacheRoomService.cs, Queueomatic/Server/Services/RoomService/IRoomService.cs, Queueomatic/Server/Services/RoomService/RoomService.cs
Added a button for creating a room while someone is logged in. 
**OBS**
This PR will identify a new [bug](https://github.com/Mojtabarezaei4/Queueomatic/issues/164). There is an [issue](https://github.com/Mojtabarezaei4/Queueomatic/issues/164) assigned to the new bug and it should be fixed separately.
close #158
=> Add UI and functionality to create a room

Queueomatic/Client/Pages/Room.razor.cs, Queueomatic/Server/Endpoints/Hubs/Room/RoomHub.cs, Queueomatic/Server/Services/CacheRoomService/CacheRoomService.cs
Close #164 and restructured some code in the cache.
=> NullReference Exception in _CacheRoomService.CleanRoom()

Queueomatic/Client/Components/EditProfile/EditProfileComponent.razor, Queueomatic/Client/Components/EditProfile/EditProfileComponent.razor.cs, Queueomatic/Client/Components/EditProfile/EditProfileComponent.razor.css, Queueomatic/Client/Components/Profile/ProfileComponent.razor.cs, Queueomatic/Server/Endpoints/User/ChangeUsername/ChangeUsernameEndpoint.cs, Queueomatic/Server/Endpoints/User/ChangeUsername/ChangeUsernameRequest.cs, Queueomatic/Server/Endpoints/User/ChangeUsername/ChangeUsernameResponse.cs
=> Add functionality to edit username

Queueomatic/Client/Components/CreateRoom/CreateRoomForm.razor, Queueomatic/Client/Components/CreateRoom/CreateRoomForm.razor.cs, Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor, Queueomatic/Client/Components/Participant/ParticipantSignupForm.razor.cs, Queueomatic/Client/Components/Profile/ProfileComponent.razor, Queueomatic/Client/Components/Profile/ProfileComponent.razor.cs, Queueomatic/Client/Components/VisitedRooms/VisitedRoomsComponent.razor, Queueomatic/Client/Components/VisitedRooms/VisitedRoomsComponent.razor.cs, Queueomatic/Client/Components/VisitedRooms/VisitedRoomsComponent.razor.css, Queueomatic/Client/Pages/Index.razor, Queueomatic/Client/Pages/Index.razor.cs, Queueomatic/Client/Pages/Index.razor.css, Queueomatic/Client/Pages/Room.razor, Queueomatic/Client/Pages/Room.razor.cs, Queueomatic/Client/Program.cs, Queueomatic/Client/Queueomatic.Client.csproj, Queueomatic/Client/Services/ManageVisitedRooms/IManageVisitedRooms.cs, Queueomatic/Client/Services/ManageVisitedRooms/ManageVisitedRooms.cs, Queueomatic/Client/Services/StoreVisitedRooms/IUpdateVisitedRooms.cs, Queueomatic/Client/Services/StoreVisitedRooms/UpdateVisitedRooms.cs, Queueomatic/Client/Shared/NavMenu.razor, Queueomatic/Client/_Imports.razor
Showing a list of "recently joined rooms" on the start page which is stored as local storage.
close #157
=> Display recently joined rooms on the home page

Queueomatic/Client/Pages/Room.razor, Queueomatic/Client/Pages/Room.razor.cs, Queueomatic/Client/Pages/Room.razor.css
=> Show room id for owner of the room in the room page

Queueomatic/Queueomatic.DataAccess/Models/Room.cs, Queueomatic/Queueomatic.DataAccess/Repositories/RoomRepository.cs, Queueomatic/Queueomatic.DataAccess/Repositories/UserRepository.cs, Queueomatic/Server/Endpoints/Participant/Delete/DeleteParticipantEndpoint.cs, Queueomatic/Server/Services/ParticipantService/ParticipantService.cs, Queueomatic/Server/Services/RoomDeletionService/RoomDeletionService.cs, Queueomatic/Server/Services/RoomService/RoomService.cs
=> Update deletion service and naming of participants
